#!/usr/bin/env python3
"""Parent Feedback Agent (Gemini Flash Lite + local heuristics)

This agent:
- Interprets the JSON output from drill_feedback.py
- Produces a short, parent-friendly summary using deterministic heuristics
- Optionally sends the draft to a lightweight LLM (Gemini 2.5 Flash Lite)
  for tone polishing, with strict instructions and low token limits

Usage:
  python parent_feedback_agent.py results/drill/foo_drill_feedback.json

Environment:
  GOOGLE_API_KEY (optional). If missing or model fails, falls back to local summary.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# Optional .env auto-load for GOOGLE_API_KEY
try:
    from dotenv import load_dotenv  # type: ignore
    load_dotenv()
except Exception:
    pass

# Unified Google GenAI client import
try:
    from google import genai  # type: ignore
    GENAI_AVAILABLE = True
except Exception:
    GENAI_AVAILABLE = False



def load_feedback_json(json_path: Path) -> Dict[str, Any]:
    """Load a drill feedback JSON file.

    Args:
        json_path: Path to the JSON file generated by drill_feedback.py

    Returns:
        Parsed JSON as a Python dict.
    """
    with json_path.open("r") as f:
        return json.load(f)


def validate_shot_data(shot: Dict[str, Any]) -> Dict[str, Any]:
    """Validate shot data and mark missing fields as N/A.

    Args:
        shot: One shot dict from the feedback JSON

    Returns:
        A dict with validated fields, N/A for missing data.
    """
    result = {}
    
    # Required fields - use N/A if missing
    result["time"] = shot.get("shot_time_sec", "N/A")
    result["knee_deg"] = shot.get("knee_bend_min_deg", "N/A")
    result["knee_score"] = shot.get("knee_bend_score", "N/A")
    result["knee_valid"] = shot.get("knee_bend_valid", "N/A")
    result["hip_drive"] = shot.get("hip_drive", "N/A")
    result["hip_drive_good"] = shot.get("hip_drive_good", "N/A")
    result["control_smoothness"] = shot.get("control_smoothness", "N/A")
    
    # Stick lift handling
    stick = shot.get("stick_lift", {})
    if stick:
        result["stick_present"] = stick.get("present", "N/A")
        result["stick_time"] = stick.get("first_time_sec", "N/A")
        result["stick_peak"] = stick.get("peak_norm", "N/A")
    else:
        result["stick_present"] = "N/A"
        result["stick_time"] = "N/A"
        result["stick_peak"] = "N/A"
    
    return result


def generate_summary_with_gemini(
    raw: Dict[str, Any],
    model_name: str = "gemini-2.5-flash-lite",
    temperature: float = 0.1,
    max_output_tokens: int = 256,
) -> str:
    """Generate parent-friendly summary using Gemini with strict instructions.

    Returns polished text, or raises an error if fails.
    """
    if not GENAI_AVAILABLE:
        raise RuntimeError("google genai client not available. Install with: pip install google-genai")

    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
        raise RuntimeError("GOOGLE_API_KEY environment variable not set")

    try:
        client = genai.Client(api_key=api_key)
        system = (
            "You are a supportive youth hockey coach. Produce ONLY the per-shot report from the provided drill JSON. "
            "Rubric: Knee (score) ≥0.7 = good; 0.4–0.69 = moderate; <0.4 = needs work. Hip drive ≥0.3 = good drive. "
            "Wrist steadiness (formerly 'control') labels: ≥0.6 smooth; ≤0.3 jerky; else mixed. "
            "Naming: say 'knee bend' for knee, 'hip drive' for hip, and 'follow-through' for stick lift. "
            "Presentation rules: Report knee bend as degrees only (use knee_bend_min_deg), NOT the raw knee score. "
            "For hip drive, include the 0..1 value and good/not good. For wrist steadiness, include only the label (no number). "
            "For follow-through, say yes/no and include time/peak if present. If a field is missing or N/A, say 'not tracked'. "
            "Output format: First line 'N shots detected: times …'; then per-shot bullets like: "
            "'time — knee bend XXX°, hip drive H.HHH (good/not good), wrist steadiness: LABEL, follow-through: yes/no'. "
            "Do NOT include any other sections (no 'What went well' or 'What to work on'). Keep it concise."
        )

        resp = client.models.generate_content(
            model=model_name,
            contents=[
                {"role": "user", "parts": [{"text": json.dumps(raw)}]},
            ],
            config={
                "system_instruction": system,
                "temperature": temperature,
                "max_output_tokens": max_output_tokens,
            },
        )

        text = (getattr(resp, "text", None) or "").strip()
        if not text:
            raise RuntimeError("Gemini returned empty response")

        return text

    except Exception as e:
        raise RuntimeError(f"Gemini API call failed: {e}")




def save_summary_text(video_or_json: Path, summary: str) -> Path:
    """Save summary next to results JSON under results/drill/ with _summary.txt suffix."""
    stem = video_or_json.stem
    out_dir = Path("results/drill")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{stem}_summary.txt"
    out_path.write_text(summary)
    return out_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Parent Feedback Agent - Interprets drill_feedback.py JSON output")
    parser.add_argument("json_path", help="Path to drill feedback JSON file")
    parser.add_argument("--model", default="gemini-2.5-flash-lite", help="Gemini model name")
    parser.add_argument("--temperature", type=float, default=0.1)
    parser.add_argument("--max_tokens", type=int, default=256)
    args = parser.parse_args()

    source_path = Path(args.json_path)
    if not source_path.exists():
        raise FileNotFoundError(f"JSON not found: {source_path}")
    
    result = load_feedback_json(source_path)

    # Always use Gemini - no fallback
    summary = generate_summary_with_gemini(
        result,
        model_name=args.model,
        temperature=args.temperature,
        max_output_tokens=args.max_tokens,
    )

    out_path = save_summary_text(source_path, summary)
    print(summary)
    print(f"\nSaved: {out_path}")


if __name__ == "__main__":
    main()


